# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dinis Vieira
title: Mobile Developer
email: dinis@dinisvieira.com
website: https://www.dinisvieira.com/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: dinisvieira
github_username:  dinisvieira
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: dinisvieira
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a Senior Software Developer (13 years) currently focusing on Mobile Development with Xamarin / MAUI (9 years). In the past I have also done Native and Hybrid Mobile Development as well as Web Development.
  Throughout the last years I was also the Team Lead of small development teams and helped my managers/companies on key technology decisions

  I am most skilled in: <mark>Mobile Development</mark> using <mark>Xamarin / MAUI</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: SiteDocs
        link: https://www.sitedocs.com/
        # link_text: boringcompany.com
        sub_title: Lead Mobile Developer
        caption: BC, Canada / 2017 - Present
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Lead Developer of Mobile Apps for iOS and Android using <mark>Xamarin.Forms</mark> and <mark>MAUI</mark>.
            - Responsible for suggesting and designing new Apps to replace older ones. New app managed to increase the development cycle drastically.
            - Implemented <mark>Automated UI Tests</mark> and CI/CD and helped with other key tech decisions.
            - This is a <mark>100% Remote</mark> position.

      - layout: left
        title: Xpand IT
        link: https://www.xpand-it.com/
        # link_text: boringcompany.com
        sub_title: Tech Lead Developer
        caption: Lisbon, Portugal / 2013 - 2017
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            -	Worked across several projects and customers usually as the Team Lead Developer.
            -	Responsible for Training and Workshops both inside the company, customers and other organizations (for example Universities).
            -	Most projects were for Mobile Development using <mark>Xamarin.Native</mark>, <mark>Xamarin.Forms</mark>, <mark>Android</mark> (Java), <mark>iOS</mark> (ObjC) but also worked on some Web Development (.Net MVC) and other R&D projects.
            -	Created a real time telemetry solution for McNamara / Mercedes using Android and Azure. [Project Video](https://www.youtube.com/watch?v=zL90RIIa0vs)
            -	Worked as a Team Lead Developer for an USA based customer building an app for mobile analytics (Windows Store App)

      - layout: left
        title: Gfi Portugal
        #link: https://www.xpand-it.com/
        #link_text: Lisbon, Portugal
        sub_title: Research & Development
        caption: Lisbon, Portugal / 2011 - 2013
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            -	Developed an Interactive Itineraries experiment using Microsoft Kinect and Google StreetView. This was showcased in an International Exhibition in Lisbon.
            -	Responsible for developing several Apps and PoCs with Phonegap, Kinect, iOS, Android, Windows Phone and Windows Store Apps.
            -	Internal Community Management: Organized several Geek/Tech Events, helped in defining internal programming practices and methodologies, presented workshops on Windows Store Apps and Mobile Web Development.
            -	Helped Sales Managers with Pre-Sales initiatives.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: top-middle
        title: Mobile App for Safety Management
        caption: Present
        link: https://www.sitedocs.com/
        link_text: SiteDocs
        additional_links:
          - title:  SiteDocs
            icon: fab fa-website
            url: https://www.sitedocs.com/
        #quote: >
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          This is an ongoing project in which I'm responsible the development of an app for Android and iOS (using Xamarin and MAUI).

          The project already existed in an unfinished state when I started working on it, so I started doing analysis on how to improve it and as a result we built a new App that has now completely replaced the old one but using improved maintainability techniques and UI/UX

      - layout: top-middle
        title: Nutrition Platform/Service
        caption: 2019
        link: https://www.tribegroup.pt/nutriservice/
        link_text: Nutri Service
        additional_links:
          - title:  Nutri Service
            icon: fab fa-website
            url: https://www.tribegroup.pt/nutriservice/
        #quote: >
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Tech Lead Developer of a Nutrition Platform/Service
          - Responsible for the high-level design and Architecture of the entire solution.
          - Development of <mark>Android</mark> and <mark>iOS</mark> mobile apps that allowed users to access the platform.
          - Development of the Backend <mark>(Azure/.Net MVC)</mark> that was used by nutritionist professionals.

      - layout: top-middle
        title: Mobile Banking App
        caption: 2016
        additional_links:
          - title:  iOS
            icon: fab fa-apple
            url: https://apps.apple.com/us/app/ca-mobile/id516082610
          - title:  Android
            icon: fab fa-android
            url: https://play.google.com/store/apps/details?id=ca.mobile.explorer&hl=en&gl=US
        #quote: >
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Team Leader and Developer of a <mark>Mobile Banking Apps</mark>. (There were two apps, one for particular users and another for companies).
          
          The app was developed with Xamarin for Android, iOS and Windows Phone, code sharing was done not only for the three platforms but also for sharing between the two app "flavors" (particular/company) which were similar in design and logic.
          
          This App was used as a <mark>case study by Xamarin</mark>.

      - layout: top-middle
        title: Xamarin Community
        caption: 2015
        link: https://www.meetup.com/XPlat-Using-Microsoft-Tools-for-Cross-Platform-Development/
        link_text: Meetup - Xplat | Using Microsoft Tools for Cross-Platform Development
        additional_links:
          - title:  Meetup - Xplat | Using Microsoft Tools for Cross-Platform Development
            icon: fab fa-meetup
            url: https://www.meetup.com/XPlat-Using-Microsoft-Tools-for-Cross-Platform-Development/
        #quote: >
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Helped create (co-founder) a User Group focused on sharing experiences about using Microsoft Tools for Cross-Platform Development. Created in strong partnership with Microsoft and Xamarin, the objective is to create a community that talks about Microsoft technologies and their integration with Open Source.
          
          The community reached about 200 members.

      - layout: top-middle
        title: Mobile Analytics App
        caption: 2015
        link: https://www.youtube.com/watch?v=0mGniLwzO6s
        link_text: Youtube
        additional_links:
          - title:  Youtube
            icon: fab fa-youtube
            url: https://www.youtube.com/watch?v=0mGniLwzO6s
        #quote: >
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Lead and Developer of a <mark>Windows App</mark> for mobile analytics platform that brings data and business intelligence to the next generation of users. The application allows for an interactive handling of all the data it's connected to.
          
          During this project, I had to work remotely most of the time and still be in constant contact with my team and also with the other company teams. I also relocated to the USA for a couple of times to work directly in the office.

      - layout: top-middle
        title: Real-Time Telemetry App/Service
        caption: 2014
        link: https://www.youtube.com/watch?v=zL90RIIa0vs
        link_text: Youtube - The Mercedes-Benz Surfboard for Garrett McNamara
        additional_links:
          - title:  The Mercedes-Benz Surfboard for Garrett McNamara
            icon: fab fa-youtube
            url: https://www.youtube.com/watch?v=zL90RIIa0vs
        #quote: >
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Mercedes-Benz exclusively developed a unique surfboard for legendary big wave rider Garrett McNamara's quest to break his own world record in NazarÃ©, Portugal.
          
          I was involved in this project to create a custom custom built telemetry for Garret McNamara and among other findings the top speed achieved was 62,4 Km/h.

      - layout: top-middle
        title: Kinect Experience
        caption: 2012
        link: https://www.youtube.com/watch?v=8jqHGYvVPaM
        link_text: Youtube - Interactive Itineraries
        additional_links:
          - title:  Interactive Itineraries
            icon: fab fa-youtube
            url: https://www.youtube.com/watch?v=8jqHGYvVPaM
        #quote: >
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Interactive Itineraries using Microsoft Kinect and Google Streetview. Users can activate navigation with body gestures and find out more information about sights, and watch videos, activate sounds. Developed by GFI Portugal and first presented at Turismo de Portugal booth in International Tourism Exhibition (Portugal) for Turismo de Portugal.
          
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: NOVA University Lisbon
        caption: 2007 - 2011
        sub_title: BSc Computer Science
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at University I managed to have the highest grade in the course final project.

          The project consisted of building a platform that integrates several information services which are accessed through a web application for mobile devices (iPhone, iPad, etc)

      - layout: left
        title: Xamarin Certified Developer
        caption: 2017
        sub_title: Xamarin
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Certification that was granted by Xamarin University after attending and passing a course on Xamarin Development.

      - layout: left
        title: Microsoft Certified Solutions Developer
        caption: 2014
        sub_title: Microsoft
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Microsoft Certified Solutions Developer: Windows Store Apps using C#.
          Microsoft Certification for designing and developing Windows Store Apps for Windows using XAML and C#

  - title: Passions
    layout: text
    content: | # this will include new lines to allow paragraphs
      <mark>Firefighter/EMT</mark>
      - Former Volunteer Firefighter and EMT (for 15 years).

      <mark>Pilot</mark>
      - General Aviation enthusiast with Private Pilot License.

      <mark>Motorcycles</mark>
      - Adventure Motorcycle enthusiast.
      
  - title: Links
    layout: text
    content: | # this will include new lines to allow paragraphs
      - [LinkedIn](https://www.linkedin.com/in/dinisvieira)
      - [Bluesky](https://bsky.app/profile/dinisvieira.com)
      - [Mastodon](https://mastodon.social/@dinisvieira){:rel="me"}
      - [Github](https://github.com/dinisvieira)
      - [TopTal](https://www.toptal.com/resume/dinis-vieira)  

    # Look at this cool image  
    # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-minimal
